### ISSUE TITLE
Randomness undermined? 

### ISSUE THREAD

**Issue by RuijieYu** [menonsamir/spiral-rs#2]
I am not sure if the following snippet would yield a perfectly random `r3` value. 
https://github.com/menonsamir/spiral-rs/blob/0f9bdc157086ea9534f70bb7d9e7f19920663e84/spiral-rs/src/number_theory.rs#L26-L28

1. The value `r1` has 64 random bits, and the value `r2` has 64 random bits. 
2. The expression `r1 << 32` generates a number whose upper 32 bits are random, and lower 32 bits are 0. 
3. The expression `(...) | r2` performs bitwise-or operation on the two operands, where the lower 32 bits are the same as that of `r2`, but each bit of the upper 32 bits have a 75% probability to be 1. 

Further, this snippet requires 128 random bits to be generated from `rng`, where if we only need to generate a random 64-bit number mod `modulus`, we would just need to generate the 64 bits directly. 

Is the current construct necessary? Or have I missed anything?

**Comment by menonsamir** [comment]
This code is directly adapted from this section of the SEAL library:
https://github.com/microsoft/SEAL/blob/main/native/src/seal/util/numth.cpp#L374

The randomness generated here does not impact any kind of security-related notion; it's just to find a primitive `degree`-th root of unity. For any input modulus, it suffices to just find *some* primitive `degree`-th root, so the randomness we use is not important.
